### PR TITLE
Add no-side-effects version of navigateToAppLink:error: and navigate:

### PR DESCRIPTION
**Pull request by biasedbit**
### Summary

- Allows app to know the type of navigation that would result of calling `BFAppLinkNavigation`'s `+navigateToAppLink:error:` or `-navigate:` without having any side effects (i.e. no navigation)
- Also adds a test to ensure same output as `+navigateToAppLink:error:` without the side effects.

### Motivation

Relying on `-navigate:` completely hands off app behavior to Bolts. These no-side-effects functions allow apps to know what behavior Bolts is going to adopt with a given `BFAppLink`.

At Timehop we want to:

- completely hand off behavior if it's an AppLink with eligible targets or;
- use one of our own web views if it's just a regular link or a link that cannot be handled by any installed apps.

### CODE REVIEW

**Comment by JosephEarl** [comment]
Needs rebase

**Comment by nlutsenko** [comment]
Hey @biasedbit, any chance you can rebase this?
Would love to accept and merge this in, since it looks like an amazing idea!
Sorry it took that much time to get back to you on this.

**Comment by biasedbit** [comment]
Thanks for finally looking into this but, y'know... It's been two *years*.

**Comment by nlutsenko** [comment]
@biasedbit, any chance you can rebase, it's still a valuable change...

**Comment by JosephEarl** [comment]
@biasedbit @nlutsenko if not I'd be willing to pick this one up if it's just a rebase that's needed

**Comment by nlutsenko** [comment]
This looks clean, but needs a single addition to the Info.plist, since we are building and testing on iOS 9 SDK:
```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>bolts</string>
</array>
```

**Comment by biasedbit** [comment]
I no longer have write permissions to the timehop repository from which I originally opened this PR. I guess we should close this and I'll re-do it from my personal account.

**Comment by nlutsenko** [comment]
Great, let's do that then. Closing this one and looking forward to the new one.

**Comment by biasedbit** [comment]
Rehashed at #245.

**Pull request closed without merging**
