### PR TITLE
Targets built with coverage data in Xcode 9 gives error

### PR DESCRIPTION
**Pull request by txaiwieser**
Solves #305 :)

### CODE REVIEW

**Comment by MikeSilvis** [comment]
Can we please get this merged?

**Comment by z4r** [comment]
Any update?

**Comment by MikeSilvis** [comment]
@baoshan @nlutsenko @valeriyvan We are now going on an entire quarter of not being able to build the facebook SDK using Carthage. This is starting to become absolutely ridiculous. Can we please get this thing merged so I can stop using an internal fork.

**Comment by txaiwieser** [comment]
Please, its a simple PR!

**Comment by nlutsenko** [comment]
Hey guys, sorry for delayed response.
I just tested master version of Bolts with Xcode 9.2 and when built via Carthage - it looks like everything is smooth and no llvm diagnostics data is getting emitted.

I understand that having code coverage disabled is blocking submission via iTunes Connect, however we depend on code coverage being turned on for instrumentation purposes (and to actually see the code coverage), so I would appreciate if you give it another go and report here if you still can't submit the app with the current master of Bolts.

If that is the case - I'll happily go ahead and change the way we do schemes so we only use code coverage on schemes meant for testing or find another way to keep these settings on for dev purposes only.

**Pull request closed without merging**
